nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ["https://kevin-lavenant.fr"]
    allow_methods: ["GET", "OPTIONS"]
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: ["Link"]
    max_age: 3600
  paths:
    "^/api/": # S'applique à toutes les routes commençant par /api/
      allow_origin: ["https://kevin-lavenant.fr"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allow_headers: ["Content-Type", "Authorization"]
      max_age: 3600
